airwallex/airwallex-payment-android

- airwallex/src/main/java/com/airwallex/android/view/CardExpiryEditText.kt
- airwallex/src/main/java/com/airwallex/android/view/ExpiryDateUtils.kt
- airwallex/src/main/res/values/strings.xml
- airwallex/src/test/java/com/airwallex/android/view/CardExpiryEditTextTest.kt
- airwallex/src/test/java/com/airwallex/android/view/CardWidgetTest.kt
- airwallex/src/test/java/com/airwallex/android/view/ExpiryDateUtilsTest.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
> Change year input to 2 digits and update validation rule

- GUIDE-zh.md
- GUIDE.md
- README-zh.md
- README.md
- build.gradle
- publish-module.gradle
Correct security-3ds naming in publish module
> Fix missing artifact

- airwallex/build.gradle
- airwallex/src/debug/res/drawable-xxhdpi/warning_background.xml
- airwallex/src/main/java/com/airwallex/android/view/AddPaymentMethodActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/AddPaymentMethodViewModel.kt
- airwallex/src/main/java/com/airwallex/android/view/AirwallexCheckoutBaseActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/AirwallexCheckoutViewModel.kt
- airwallex/src/main/java/com/airwallex/android/view/CardWidget.kt
- airwallex/src/main/java/com/airwallex/android/view/WarningView.kt
- airwallex/src/main/java/com/airwallex/android/view/inputs/CardNumberTextInputLayout.kt
- airwallex/src/main/res/drawable/airwallex_ic_warning.xml
- airwallex/src/main/res/layout/activity_add_card.xml
- airwallex/src/main/res/layout/warning_view.xml
- airwallex/src/main/res/values/strings.xml
- airwallex/src/test/java/com/airwallex/android/view/AddPaymentMethodViewModelTest.kt
- airwallex/src/test/java/com/airwallex/android/view/AirwallexCheckoutViewModelTest.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexPaymentManager.kt
- components-core/src/main/java/com/airwallex/android/core/PaymentManager.kt
- components-core/src/main/java/com/airwallex/android/core/model/ConfirmPaymentIntentParams.kt
- components-core/src/test/java/com/airwallex/android/core/AirwallexPaymentManagerTest.kt
- components-core/src/test/java/com/airwallex/android/core/model/ConfirmPaymentIntentParamsTest.kt
- ui-core/src/main/res/values/colors.xml
This adds warning view to card payment screen when
- UnionPay card input is detected & save card option is switched on
> [MOB-1310] Add warning when saving UnionPay card

- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsActivity.kt
| Before | After |
| --- | --- |
| <img width="354" alt="Screenshot 2023-06-12 at 15 23 30" src="https://github.com/airwallex/airwallex-payment-android/assets/107159278/f50c62de-9bd7-4427-9758-6cebfa9bf626"> | <img width="356" alt="Screenshot 2023-06-13 at 17 17 43" src="https://github.com/airwallex/airwallex-payment-android/assets/107159278/1d830676-00ce-4fc2-818a-4accfc931419"> |
> [MOB-1594] Show schema field when bank list is empty

- googlepay/src/main/AndroidManifest.xml
- googlepay/src/main/java/com/airwallex/android/googlepay/GooglePayLauncherActivity.kt
- googlepay/src/main/java/com/airwallex/android/googlepay/GooglePayLauncherViewModel.kt
- googlepay/src/main/java/com/airwallex/android/googlepay/PaymentsUtil.kt
- googlepay/src/test/java/com/airwallex/android/googlepay/GooglePayLauncherViewModelTest.kt
- Restrict activity recreation
- Refactor load payment data task to view model
> chore: prevent recreating activity when orientation changes

- airwallex/src/main/java/com/airwallex/android/view/AddPaymentMethodActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/CardWidget.kt
- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsViewModel.kt
- airwallex/src/main/java/com/airwallex/android/view/inputs/AirwallexTextInputLayout.kt
- airwallex/src/test/java/com/airwallex/android/view/PaymentMethodsViewModelTest.kt
- components-core/build.gradle
- components-core/src/main/AndroidManifest.xml
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexPaymentSession.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexRecurringWithIntentSession.kt
- components-core/src/main/java/com/airwallex/android/core/ClientSecretRepository.kt
- components-core/src/main/java/com/airwallex/android/core/TokenManager.kt
- components-core/src/test/java/com/airwallex/android/core/ClientSecretRepositoryTest.kt
- googlepay/src/main/java/com/airwallex/android/googlepay/GooglePayLauncherActivity.kt
> [APAM-17]integrate risk sdk

- airwallex/src/main/java/com/airwallex/android/AirwallexStarter.kt
- airwallex/src/main/java/com/airwallex/android/view/AddPaymentMethodActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/AddPaymentMethodActivityLaunch.kt
- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsActivity.kt
- card/src/main/java/com/airwallex/android/card/CardComponent.kt
- components-core/src/main/java/com/airwallex/android/core/ActionComponent.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexPaymentStatus.kt
- components-core/src/test/java/com/airwallex/android/core/AirwallexPaymentStatusTests.kt
- components-core/src/test/java/com/airwallex/android/core/AirwallexPluginsTest.kt
- googlepay/src/main/java/com/airwallex/android/googlepay/GooglePayComponent.kt
- googlepay/src/test/java/com/airwallex/android/googlepay/GooglePayComponentTest.kt
- redirect/src/main/java/com/airwallex/android/redirect/RedirectComponent.kt
- wechat/src/main/java/com/airwallex/android/wechat/WeChatComponent.kt
Provide payment consent ID for successful card saving sessions
> [APAM-5]Provide payment consent ID for successful card saving sessions

- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexConfiguration.kt
- components-core/src/main/java/com/airwallex/android/core/log/AirwallexLogger.kt
- sample/src/main/java/com/airwallex/paymentacceptance/SampleApplication.kt
Collect local logs in local file system if needed
> [APAM_22]Collect local logs in local file system if needed

- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsActivity.kt
- card/src/main/java/com/airwallex/android/card/CardComponent.kt
- card/src/main/java/com/airwallex/android/card/view/cvc/PaymentCheckoutActivity.kt
- card/src/main/java/com/airwallex/android/card/view/dcc/DccActivity.kt
- components-core/src/main/java/com/airwallex/android/core/ActionComponent.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/test/java/com/airwallex/android/core/AirwallexPluginsTest.kt
- googlepay/src/main/java/com/airwallex/android/googlepay/GooglePayComponent.kt
- googlepay/src/test/java/com/airwallex/android/googlepay/GooglePayComponentTest.kt
- redirect/src/main/java/com/airwallex/android/redirect/RedirectComponent.kt
- sample/build.gradle
- sample/src/main/java/com/airwallex/paymentacceptance/ui/SplashActivity.kt
- wechat/src/main/java/com/airwallex/android/wechat/WeChatComponent.kt
add leak canary 
check and fix memory leak issue
> [APAM-53]add leak canary and fix memory leak issue

- sample/src/main/java/com/airwallex/paymentacceptance/ui/APIIntegrationActivity.kt
- sample/src/main/java/com/airwallex/paymentacceptance/ui/widget/CustomerDialog.kt
- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/APIIntegrationViewModel.kt
- sample/src/main/res/layout/activity_api_integration.xml
fix:
1.exception when using recurring saved card to finish payment.
2.verify 3ds challenge for Google Pay is missing
> bugfix for apam-18

- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- sample/src/main/java/com/airwallex/paymentacceptance/repo/PACheckoutDemoRepository.kt
1.remove the requireNotNull check for initialPaymentIntentId.
2.add the referrer_data parameter when calling the createIntent API.
> [APMA-66]remove the requireNotNull check for initialPaymentIntentId.

- MIGRATING.md
Create MIGRATING.md to describe the API changes during version upgrades.
> [APAM-59] create MIGRATING.md

- airwallex/build.gradle
- build.gradle
- card/build.gradle
- components-core/build.gradle
- googlepay/build.gradle
- gradle/scripts/publish-snapshot.gradle
- publish-module.gradle
- redirect/build.gradle
- sample/build.gradle
- security-3ds/build.gradle
- ui-core/build.gradle
- wechat/build.gradle
Created an add publish-snapshot.gradle file to publish arr to the local Maven repository
> [APAM-67]add publish-snapshot.gradle

- GUIDE-zh.md
- GUIDE.md
- airwallex/src/main/java/com/airwallex/android/AirwallexStarter.kt
- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsActivity.kt
- airwallex/src/main/java/com/airwallex/android/view/PaymentMethodsViewModel.kt
- airwallex/src/test/java/com/airwallex/android/view/PaymentMethodsViewModelTest.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- redirect/src/main/java/com/airwallex/android/redirect/RedirectComponent.kt
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/airwallex/paymentacceptance/ui/APIIntegrationActivity.kt
- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/APIIntegrationViewModel.kt
- sample/src/main/res/layout/activity_api_integration.xml
- ui-core/src/main/java/com/airwallex/android/ui/AirwallexActivityLaunch.kt
support redirect component low level
but only one-off payment is supported
> [APAM-58] support redirect component low level

- airwallex/src/main/java/com/airwallex/android/AirwallexStarter.kt
- components-core/src/main/java/com/airwallex/android/core/Airwallex.kt
- components-core/src/main/java/com/airwallex/android/core/AirwallexPlugins.kt
- components-core/src/test/java/com/airwallex/android/core/AirwallexPluginsTest.kt
refactor the initialize method of Airwallex.
> [APAM-72]refactor the initialize method of Airwallex.

- airwallex/src/test/java/com/airwallex/android/view/CardWidgetTest.kt
- sample/src/main/AndroidManifest.xml
fix the problem with the app icon not showing up.
> chore: fix the problem with the app icon not showing up.

- components-core/src/main/java/com/airwallex/android/core/model/PaymentMethod.kt
add the setNumberType method to the Card class.
> chore: add the setNumberType method to the Card class.

- sample/src/main/java/com/airwallex/paymentacceptance/Constant.kt
- sample/src/main/java/com/airwallex/paymentacceptance/Settings.kt
- sample/src/main/java/com/airwallex/paymentacceptance/repo/PACheckoutDemoRepository.kt
- sample/src/main/java/com/airwallex/paymentacceptance/ui/APIIntegrationActivity.kt
- sample/src/main/java/com/airwallex/paymentacceptance/ui/SettingActivity.kt
- sample/src/main/java/com/airwallex/paymentacceptance/ui/widget/DemoCardDialog.kt
fix the issue where environment switching fails.
> [AMAP-116] fix the issue where environment switching fails.

- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/APIIntegrationViewModel.kt
- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/UIIntegrationViewModel.kt
[fix the issue where checkoutMode switching fails.](https://github.com/airwallex/airwallex-payment-android/pull/183)
>  [APAM-215]Demo app UI integration switch mode

- sample/src/main/java/com/airwallex/paymentacceptance/Constant.kt
- sample/src/main/java/com/airwallex/paymentacceptance/Settings.kt
- sample/src/main/java/com/airwallex/paymentacceptance/ui/SettingActivity.kt
- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/UIIntegrationViewModel.kt
- sample/src/main/res/layout/activity_setting.xml
- sample/src/main/res/xml/settings.xml
> [APAM-226] Add force 3ds setting

- sample/src/main/java/com/airwallex/paymentacceptance/ui/widget/DropdownPickerView.kt
- sample/src/main/java/com/airwallex/paymentacceptance/viewmodel/SettingViewModel.kt
fix issues:
1.change setting items will reset env to staging always.
2.generate customer id crash when customer id is error
> [APAM-228]change setting items will reset env to staging always

- airwallex/src/main/java/com/airwallex/android/view/composables/common/PaymentMethodTabCard.kt
- ui-core/src/main/java/com/airwallex/android/ui/composables/AirwallexColor.kt
- ui-core/src/main/java/com/airwallex/android/ui/composables/AirwallexTheme.kt
- ui-core/src/main/res/values/colors.xml
[Screen_recording_20250724_143948.webm](https://github.com/user-attachments/assets/4c27c9ff-a693-4ce4-abd1-914e88b66292)
> feat: support tint color

- .github/workflows/deploy-docs.yml
- build.gradle
- gradle.properties
- Apply dokka
- Add github action workflow
> [APAM-369] Generate api docs
